spring.application.name=backend
spring.profiles.active=dev
spring.config.import=optional:classpath:secrets.properties

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml