spring.application.name=backend

spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/gemstore
spring.datasource.username=postgres
spring.datasource.password=Musha123$

security.jwt.secret=zvDUN+vJWR7EW9lE6M7QVAjsOEXM7Zog1q5Kolags84=
security.jwt.ttl-seconds=3600

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# ===============================================
# OAUTH2 CLIENT CONFIGURATION
# ===============================================

# --- Google Provider Configuration ---
spring.security.oauth2.client.registration.google.client-id=141642556185-rg18v4rdhubfukb4507bdoo1hgsit6vb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google